spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: coco
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
file:
  upload-dir: D:\diploma\coco\uploads